# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.uppercase.transformer:
        class: AppBundle\Transformer\UppercaseTransformer
        arguments: ['@logger']

    app.uppercase.twig_extension:
        class: AppBundle\Twig\MyUppercaseExtension
        arguments: ['@app.uppercase.transformer']
        # or we can use autowire: true
        tags:
            - { name: twig.extension }
