# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.uppercase.twig_extension:
        class: AppBundle\Twig\MyUppercaseExtension
        tags:
            - { name: twig.extension }